#!/usr/bin/env sh

#CC=/usr/bin/arm-linux-gnueabi-gcc
#AS=/usr/bin/arm-linux-gnueabi-as
CC=arm-oe-linux-gnueabi-gcc
AS=arm-oe-linux-gnueabi-as
#CC=/usr/bin/arm-linux-gnueabihf-gcc
#AS=/usr/bin/arm-linux-gnueabihf-as
set -ex

./configure --no-graph -prefix /home/kakadu/trik/ocaml-dist -host armv5te-oe-linux-gnueabi \
    -cc "$CC" -as "$AS" -aspp "arm-oe-linux-gnueabi-gcc -c" \
    -no-shared-libs -libs \
    #-no-ocamldoc -no-ocamlbuild -no-debugger  \


echo "MY_LLP=LD_LIBRARY_PATH=/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/lib" >> config/Makefile




